/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import control.controladorMateriaPrima;
import control.controladorProduto;
import model.MateriaPrima;
import model.MateriaPrimaPorProduto;
import model.Produto;

/**
 *
 * @author murilo
 */
public class UICadastrarProduto extends javax.swing.JFrame {

    /**
     * Creates new form UICadastrarProduto
     */
    List<MateriaPrima> listaMateriaPrima;
    double total = 0;
    public UICadastrarProduto() throws ClassNotFoundException, SQLException {
        initComponents();
        listaMateriaPrima = controladorMateriaPrima.consultar();
        int n = listaMateriaPrima.size();
        for(int i=0; i<n; i++){
            comboMateriaPrima.addItem(listaMateriaPrima.get(i).getNome());
        }
        
        String[] columnNames = {"Materia prima",
            "Quantidade",
            "Valor Un.",
            "Custo por Peça"};
        Object[][] data = null;
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        tblMateriaPrima.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboMateriaPrima = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMateriaPrima = new javax.swing.JTable();
        addMateriaPrima = new javax.swing.JButton();
        removeMateriaPrima = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        btnnovaMateriaPrima = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Produto");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Descrição:");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        jLabel3.setText("Matérias Primas:");

        jLabel4.setText("Matéria-Prima:");

        jLabel5.setText("Quantidade:");

        tblMateriaPrima.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMateriaPrima);

        addMateriaPrima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/add.png"))); // NOI18N
        addMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMateriaPrimaActionPerformed(evt);
            }
        });

        removeMateriaPrima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/remove.png"))); // NOI18N
        removeMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMateriaPrimaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Total: R$");

        txtTotal.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtTotal.setText("0.00");

        btnnovaMateriaPrima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/add.png"))); // NOI18N
        btnnovaMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovaMateriaPrimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(removeMateriaPrima)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addMateriaPrima))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnnovaMateriaPrima)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(comboMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnnovaMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotal))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        double min = 0.00;
        double value = 0.50;
        double max = 1000.00;
        double stepSize = 0.50;
        SpinnerNumberModel model = new SpinnerNumberModel(value, min, max, stepSize);

        txtQuantidade.setModel(model);
        JSpinner.NumberEditor editor = (JSpinner.NumberEditor)txtQuantidade.getEditor();
        DecimalFormat format = editor.getFormat();
        format.setMinimumFractionDigits(2);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMateriaPrimaActionPerformed
        // TODO add your handling code here:
        /**
        * Quando o usuario clicar no botão para adicionar um novo endereço,
        * será pego o modelo atual da tabela (linhas ja existentes) e então
        * adicionada uma nova linha correspondente aos valores preechidos.
        */

        DefaultTableModel dtm = (DefaultTableModel)tblMateriaPrima.getModel();
        
        double quantidade = (double) txtQuantidade.getValue();
        MateriaPrima materiaPrima = listaMateriaPrima.get(comboMateriaPrima.getSelectedIndex());
        double valorAcumulado =  quantidade * materiaPrima.getValorUnd();
        total += valorAcumulado;
        Object[] linha = {materiaPrima.getNome(),
                          txtQuantidade.getValue(),
                          materiaPrima.getValorUnd(),
                          valorAcumulado
        };
        dtm.addRow(linha);
        tblMateriaPrima.setModel(dtm);
        String strTotal = String.valueOf(total);
        txtTotal.setText(strTotal);
    }//GEN-LAST:event_addMateriaPrimaActionPerformed

    private void removeMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMateriaPrimaActionPerformed
        // TODO add your handling code here:
        /**
        * Quando o usuario clicar no botão excluir endereco, será pego a linha
        * selecionada na tabela e então está será removida, caso não tenha uma linha
        * selecionada, nada será feito.
        */
        int linha = tblMateriaPrima.getSelectedRow(); //pega a linha selecionada
        if(linha >= 0){ //se realmente houver uma linha selecionada, então
            DefaultTableModel dtm = (DefaultTableModel)tblMateriaPrima.getModel();
            String strValor = dtm.getValueAt(linha, 3).toString();
            double valor = Double.valueOf(strValor);
            total -= valor;
            strValor = String.valueOf(total);
            txtTotal.setText(strValor);
            dtm.removeRow(linha);
            tblMateriaPrima.setModel(dtm);
        }
    }//GEN-LAST:event_removeMateriaPrimaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnnovaMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovaMateriaPrimaActionPerformed
        try {
            // TODO add your handling code here:
            new UICadastrarMateriaPrima().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UICadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnnovaMateriaPrimaActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        try {
            listaMateriaPrima = controladorMateriaPrima.consultar();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UICadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        int n = listaMateriaPrima.size();
        comboMateriaPrima.removeAllItems();
        for(int i=0; i<n; i++){
            comboMateriaPrima.addItem(listaMateriaPrima.get(i).getNome());
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        int qntd = tblMateriaPrima.getRowCount(); // pega a quantidade de linhas da tabela
        DefaultTableModel dtm = (DefaultTableModel)tblMateriaPrima.getModel(); //responsavel pela leitura da tabela
        List<MateriaPrimaPorProduto> materiasPrima = new ArrayList<>(); //cria uma lista de materiasPrimasPorProduto (ver o diagrama de classe)
        Produto produto = new Produto(); //cria um novo produto
        boolean add = false; //validará a inserção
        for(int i=0; i<qntd; i++){
            MateriaPrimaPorProduto materiaPrima = new MateriaPrimaPorProduto(); //cria uma nova MateriaPrimaPorProduto
            
            try {
                listaMateriaPrima = controladorMateriaPrima.consultar(dtm.getValueAt(i, 0).toString()); //realiza uma busca na materia prima que esta na linha i
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(UICadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
            materiaPrima.setMateriaPrima(listaMateriaPrima.get(0)); //atribui a materia prima para a materiaPrimaPorProduto, caso a busca tenha retornado mais de um valor, sempre pegará o primeiro
            String valor = dtm.getValueAt(i, 1).toString(); //pega o campo quantidade
            double valorD = Double.valueOf(valor); //transforma a quantidade em double
            materiaPrima.setQuantidade(valorD); //atribui a quantidade no objeto materiaPrima
            valor = dtm.getValueAt(i, 3).toString(); //pega o campo valorAcumulado
            valorD = Double.valueOf(valor); //transforma para double
            materiaPrima.setTotalAcumulado(valorD); //atribui o valorAcumulado no objeto materiaPrima
            materiasPrima.add(materiaPrima); //adiciona a MateriaPrimaPorProduto na lista
        }
        produto.setNome(txtNome.getText()); //atribui valores para o produto
        produto.setDescricao(txtDescricao.getText());
        produto.setMateriasPrimas(materiasPrima);
        produto.setTotal(total);
        try {
            add = controladorProduto.add(produto); //envia para o controlador fazer a inserção do produto
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UICadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(add){ //caso consiga fazer a inserção
            JOptionPane.showMessageDialog(rootPane, "Produto cadastrado com sucesso!");
            this.dispose();
        } else{ //caso nao consiga
            JOptionPane.showMessageDialog(rootPane, "Produto não cadastrado!");
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UICadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UICadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UICadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UICadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UICadastrarProduto().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(UICadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(UICadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMateriaPrima;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnnovaMateriaPrima;
    private javax.swing.JComboBox comboMateriaPrima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeMateriaPrima;
    private javax.swing.JTable tblMateriaPrima;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JSpinner txtQuantidade;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
