/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solp.view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import solp.control.controladorMateriaPrima;
import solp.model.MateriaPrima;

/**
 *
 * @author murilo
 */
public class UIConsultarMateriaPrima extends javax.swing.JFrame {

    /**
     * Creates new form UIConsultarMateriaPrima
     */
    List<MateriaPrima> listaMateriaPrima;
    public UIConsultarMateriaPrima() throws ClassNotFoundException, SQLException {
        initComponents();
        listaMateriaPrima = controladorMateriaPrima.consultar();
        String[] columnNames = {"Id",
            "Nome",
            "Fornecedor",
            "Unidade",
            "Valor Unt.",
            "Descrição"};
        Object[][] data = null;
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        
         
        int n = listaMateriaPrima.size();
        for(int i=0; i<n; i++){
            Object[] linha = {listaMateriaPrima.get(i).getId().toString(), 
                              listaMateriaPrima.get(i).getNome(), 
                              listaMateriaPrima.get(i).getFornecedor().getRazaoSocial(),
                              listaMateriaPrima.get(i).getUnd(),
                              listaMateriaPrima.get(i).getValorUnd(),
                              listaMateriaPrima.get(i).getDescricao()};
            dtm.addRow(linha);
        }
        
        
        tblMateriaPrima.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMateriaPrima = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Matéria Prima");

        jLabel1.setText("Nome:");

        tblMateriaPrima.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMateriaPrima);

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        try {
            // TODO add your handling code here:
            listaMateriaPrima = controladorMateriaPrima.consultar(txtNome.getText());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(UIConsultarMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] columnNames = {"Id",
            "Nome",
            "Fornecedor",
            "Unidade",
            "Valor Unt.",
            "Descrição"};
        Object[][] data = null;
        DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
        
         
        int n = listaMateriaPrima.size();
        for(int i=0; i<n; i++){
            Object[] linha = {listaMateriaPrima.get(i).getId().toString(), 
                              listaMateriaPrima.get(i).getNome(), 
                              listaMateriaPrima.get(i).getFornecedor().getRazaoSocial(),
                              listaMateriaPrima.get(i).getUnd(),
                              listaMateriaPrima.get(i).getValorUnd(),
                              listaMateriaPrima.get(i).getDescricao()};
            dtm.addRow(linha);
        }
        
        
        tblMateriaPrima.setModel(dtm);
    }//GEN-LAST:event_txtNomeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIConsultarMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIConsultarMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIConsultarMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIConsultarMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UIConsultarMateriaPrima().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(UIConsultarMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMateriaPrima;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
